### ISSUE TITLE
How can I solve this problem, Thank you!

### ISSUE THREAD

**Issue by TGISer** [zhangweichen2006/iCAN#1]
Replacing the following state from initialized resnet50 : ['fc.weight', 'fc.bias']
=> no checkpoint model
Epoch 0/19
----------
Phase: train lr_mult: 0.8176 Loss: 1.5282 D_loss: 0.6252 D1_loss: 0.6929 D2_loss: 0.6931 D3_loss: 0.6930 Acc: 0.5495 D_Acc: 0.6557
Total loss: 2.1180, w_main: 0.5000, 1: 0.1333, 2: 0.1333, 3: 0.1333
Phase: test Loss: 1.5703 Acc: 0.5167
Best Test Accuracy: 0.5167

Epoch 1/19
----------
Phase: train lr_mult: 0.5946 Loss: 0.7955 D_loss: 0.6125 D1_loss: 0.6920 D2_loss: 0.6927 D3_loss: 0.6928 Acc: 0.7661 D_Acc: 0.6575
Total loss: 1.3787, w_main: 0.5000, 1: 0.1333, 2: 0.1333, 3: 0.1333
Phase: test Loss: 1.2975 Acc: 0.6295
Best Test Accuracy: 0.6295

Epoch 2/19
----------
Phase: train lr_mult: 0.5030 Loss: 0.5793 D_loss: 0.6147 D1_loss: 0.6912 D2_loss: 0.6923 D3_loss: 0.6927 Acc: 0.8277 D_Acc: 0.6611
Total loss: 1.1635, w_main: 0.5000, 1: 0.1333, 2: 0.1333, 3: 0.1333
Phase: test Loss: 1.2971 Acc: 0.6624
Best Test Accuracy: 0.6624

Epoch 3/19
----------
Phase: train lr_mult: 0.4387 Loss: 0.4751 D_loss: 0.6359 D1_loss: 0.6907 D2_loss: 0.6920 D3_loss: 0.6927 Acc: 0.8574 D_Acc: 0.6386
Total loss: 1.0698, w_main: 0.5000, 1: 0.1333, 2: 0.1333, 3: 0.1333
Phase: test Loss: 0.8034 Acc: 0.7400
Best Test Accuracy: 0.7400

Epoch 4/19
----------
E:/coding/domain adaptation/iCAN-master/a2w.py:245: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  top_prob, top_label = torch.topk(F.softmax(class_t)[0], 1)
Pseudo size: 33 confid_threshold: 0.9020
E:/coding/domain adaptation/iCAN-master/a2w.py:1064: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  log_probs_flat = F.log_softmax(logits_flat)
Phase: Pseudo_train Lr: 1.0000 Loss: 0.0169 Acc: 0.9706 Disc_Lam: 0.004867 Disc_bias: 0.5000 
Traceback (most recent call last):
  File "E:/coding/domain adaptation/iCAN-master/a2w.py", line 1165, in <module>
    main()
  File "E:/coding/domain adaptation/iCAN-master/a2w.py", line 1162, in main
    model = train_model(model_dann, optimizer_ft, optimizer_pseudo, exp_lr_scheduler, pseudo_lr_scheduler, num_epochs=total_epochs, start_epoch=start_epoch, best_acc=best_prec, loaded_model = loadmodel, draw_dict=draw_dict)
  File "E:/coding/domain adaptation/iCAN-master/a2w.py", line 521, in train_model
    class_weights_tensor = torch.cat((source_weight_tensor, pseudo_weights_tensor),0)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 1 and 2 at c:\anaconda2\conda-bld\pytorch_1519501749874\work\torch\lib\th\generic/THTensorMath.c:2888

Process finished with exit code 1

**Comment by zhangweichen2006** [comment]
Hi, seems you are using different pytorch version other than pytorch 0.2. In this occasion, pseudo weights tensor might be 0. So you can check the length of pseudo_weights_tensor, if it is 0, then  class_weights_tensor = source_weight_tensor. Thanks.

**Comment by TGISer** [comment]
Thank you! I will try it!
