### ISSUE TITLE
希望可以分享一下Image-clef数据集

### ISSUE THREAD

**Issue by wyf0912** [zhangweichen2006/iCAN#4]
因为在比赛的网站上找的数据集是提取特征后的数据

**Comment by zhangweichen2006** [comment]
The dataset is published in https://github.com/thuml/Xlearn/tree/master/caffe by Long et al.

Here is the download link https://drive.google.com/file/d/0B9kJH0-rJ2uRS3JILThaQXJhQlk/view

**Comment by wyf0912** [comment]
> The dataset is published in https://github.com/thuml/Xlearn/tree/master/caffe by Long et al.
> 
> Here is the download link https://drive.google.com/file/d/0B9kJH0-rJ2uRS3JILThaQXJhQlk/view

太感谢了 thx
