### ISSUE TITLE
domain classfier的准确率较低

### ISSUE THREAD

**Issue by wyf0912** [zhangweichen2006/iCAN#5]
我在训练office->webcam的时候 发现l1 domain classfier 准确率最高只能达到60

**Comment by zhangweichen2006** [comment]
@wyf0912 domain classifier准确率理论上越接近50越好，目的是为了让source和target samples分不清

**Comment by wyf0912** [comment]
谢谢回复 不好意思我可能没有说清... 因为我看到您 ./graph目录下有一张几个domain classfier准确率的图 那张图上l1 domain classfier的准确率超过了80%..

但我在pytorch0.41的环境下跑代码只达到了60多..不知道是什么原因

**Comment by zhangweichen2006** [comment]
确实我这里pytorch 0.4和0.2版本的结果不太一样，而且domain adaptation主要是训练target domain的accuracy，sub domain classfier的准确率是会波动比较大的，每次学习都不一样，一般学出来的结果是l1或者l2 classfier 准确率最高，l3和l4(main)比较低，也就显示了论文中前面层分得清，后面分不清的情况
