### ISSUE TITLE
Error in code 

### ISSUE THREAD

**Issue by vinodkkurmi** [zhangweichen2006/iCAN#6]
Hi @zhangweichen2006  I am gettign following errro when run the a2w.py file 

class_weights_tensor = torch.cat((source_weight_tensor, pseudo_weights_tensor),0)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 1 and 2 at /opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/TH/generic/THTensorMath.c:2888

**Comment by zhangweichen2006** [comment]
I think you might use the wrong Pytorch version. Try to use the corresponding version to run the code, run v1 with Pytorch 0.2 or 0.3 and v2 with Pytorch 0.4.

**Comment by Ellenisawake** [comment]
Running v1 with PyTorch 0.3 gives the same error, while it did not happen while running v2 with PyTorch 0.4.

**Comment by zhangweichen2006** [comment]
I've changed the code to deal with the dimension problem for v0.3. Hope it will work.
