### ISSUE TITLE
Hello, can you share the dataset in the code?

### ISSUE THREAD

**Issue by Mamba-ZYD** [zhangweichen2006/iCAN#8]
Hello, can you share the dataset in the code?In this directory, what is your directory structure?
data_dir = '/home/wzha8158/datasets/Office/domain_adaptation_images/'

**Comment by zhangweichen2006** [comment]
The dataset link can be found here: https://drive.google.com/open?id=0B4IapRTv9pJ1WGZVd1VDMmhwdlE
in https://people.eecs.berkeley.edu/~jhoffman/domainadapt/#datasets_code. The structure is like data_root/classes/images
