### ISSUE TITLE
Need clarification for training process

### ISSUE THREAD

**Issue by Griffintaur** [zhangweichen2006/iCAN#9]
I just want to clearly understand the training process.
Let say at epoch `t` you trained the model, you calculated the accuracy and select pseudo labels and their weights and computed the corresponding loss.
Now after back-propagating, the total loss do you maintain the pseudo label over next epoch i.e for next `epoch t+1` you keep the pseudo labelled target samples for next epoch or then select another set of pseudo-labelled data, in this you are increasing the size of pseudo labelled target data
or 
is it the case in every epoch you just select the pseudo label target data and use it compute the loss without maintaining any state between two epochs.

**Comment by zhangweichen2006** [comment]
Sorry for the late reply. We independently select another set of pseudo-labelled data, as some incorrectly predicted samples might be corrected in the later epoch.
